schema_version: 1

context:
  py_ver: PY_VER
  version: 0.13.0

package:
  name: sumy
  version: ${{ version }}

source:
- url: https://files.pythonhosted.org/packages/source/s/sumy/sumy-${{ version }}.tar.gz
  sha256: 5bdf1af5286801a74e9b5fd3aa58c3ab2316318a42de3c12f38f9737bee6cfc2


build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sumy = sumy.__main__:main
      - sumy-${{ py_ver }} = sumy.__main__:main
      - sumy_eval = sumy.evaluation.__main__:main
      - sumy_eval-${{ py_ver }} = sumy.evaluation.__main__:main

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - breadability >=0.1.20
    - docopt-ng >=0.6.3
    - lxml-html-clean >=0.1.0
    - nltk !=3.10.1,>=3.9.1
    - pycountry >=18.2.23
    - python >=${{ python_min }}
    - requests >=2.7.0
    - setuptools >=78.1.1,<82

tests:
  - python:
      imports:
        - sumy
        - sumy.evaluation
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - sumy --help
      - sumy-${{ py_ver }} --help
      - sumy_eval --help
      - sumy_eval-${{ py_ver }} --help

about:
  summary: Module for automatic summarization of text documents and HTML pages.
  license: Apache-2.0
  license_file: LICENSE.md
  homepage: https://github.com/miso-belica/sumy

extra:
  recipe-maintainers:
    - nicornk
    - tobiasploetz
